remote_theme: "mmistakes/minimal-mistakes@4.24.0"

url: "https://netsuchanya.github.io"
baseurl: ""
repository: "netsuchanya/netsuchanya.github.io"

title: "Geoscience Student"
name: "Suchanya Mitprayoon"
description: "Suchanya Mitprayoon's academic portfolio"
locale: "en-US"
title_separator: "-"

author:
  avatar: "images/Suchanya.jpg"
  name: "Suchanya Mitprayoon"
  pronouns: "she/her"
  bio: "Geophysicist"
  location: "Bangkok"
  employer: "Mahidol University"
  email: "suchanya.mit@gmail.com"
  github: "netsuchanya"

include:
  - _pages

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
